### ISSUE TITLE
Contrarian thought in maths education

### ISSUE THREAD

**Issue by ErikBjare** [lunduniversity/schoolprog#10]
As someone who have never been very happy with the current state of maths education, I have naturally been drawn towards the contrarian ideas of how it should be. Since I'm slightly worried that the introduction of programming into school curricula might go down the same dark path, I'd like us to at least try and get these ideas out there, because I really think there is something to them. @exoji2e probably agrees with me.

Here are some of my favorites:

 - [A Mathematicians Lament](https://www.maa.org/external_archive/devlin/LockhartsLament.pdf) by Paul Lockhart ([Wikipedia](https://en.wikipedia.org/wiki/A_Mathematician%27s_Lament))
 - [Judging Books by Their Covers](http://www.textbookleague.org/103feyn.htm) by Richard Feynman
 - [The teaching philosophy of fast.ai](http://www.fast.ai/2016/10/08/teaching-philosophy/), an online deep learning course - heavily inspired by Lockhart

My hope is that we could write up a "teaching philosophy" document similar to the one written for fast.ai where we try to raise awareness about these issues. I think it would serve as a great exercise not only for the teachers and students who might read it but also for ourselves.

**Comment by exoji2e** [comment]
Yes please. 

I haven't read the fast.ai teaching philosophy, but my initial thoughts on what should be included is:
- Teach how to recover the knowledge 
- Making sure everyone is well understood with the idea that making errors in the beginning is the fastest way of learning. Just try things out.
- Make sure to point out things that are hard at first sight (inlärningströsklar) and be very clear and gentle while explaining about it. Adopt multiple ways of explaining it.
- Specify what the goal of a course/exercise is. What are we trying to teach, and why is that important. What can the techniques taught be used for? 
- Move away (or separate) from pure arithmetic like Lockhart wants.
- Having real applications in mind when creating and presenting problems.
- Make sure the applied problems makes sense, not like the one Feynman describes where the students are supposed to add up temperatures for planets.

**Comment by gorelhedin** [comment]
Good points. But closing this issue for now.
