### ISSUE TITLE
Set up website

### ISSUE THREAD

**Issue by ErikBjare** [lunduniversity/schoolprog#12]
Stuff left to do:

 - [x] Configuration
 - [x] Instructions for how to build the site locally
 - [x] Continuous integration (automatic hosting of master branch)
 - [x] Google Analytics
 - [ ] Design
   - [x] Navigation
   - [x] Site structure
   - [ ] Styling

**Comment by gorelhedin** [comment]
Perhaps move all web related stuff to subdir `web`??

**Comment by ErikBjare** [comment]
That's actually not possible, but I can look into if there are some individual files/folders which can be moved.

**Comment by gorelhedin** [comment]
Ok, no problem. Could you add some instructions for building and trying out the web site? I'd like to play around a bit before our meeting on Wednesday.

**Comment by ErikBjare** [comment]
The site is almost working now, it's just that the SCSS isn't being built into CSS correctly. I'll look into it.

**Comment by ErikBjare** [comment]
It's working now! 😃 

https://lunduniversity.github.io/schoolprog/

**Comment by gorelhedin** [comment]
Tjusigt!!!
Hittade några buggar:
- Texten kommer dubbelt för "guess the number" och "bråkspel"
- Cheatsheet för python visas som markdown text
- Går det att få lokala länkar till md omskrivna, så att vi kan ha kvar dem som md (så det funkar både direkt på github och på siten)?

**Comment by ErikBjare** [comment]
Fixing the first two points.

I'll attempt to fix the third point using: https://github.com/benbalter/jekyll-relative-links

**Comment by ErikBjare** [comment]
@gorelhedin Managed to get it working! Enjoy 😃

**Comment by gorelhedin** [comment]
Wonderful! Looks really great!!!

**Comment by ErikBjare** [comment]
@gorelhedin Fixed the top menu as well now so that all the pages aren't listed there. Closing this since the rest is polish 👍
