### ISSUE TITLE
Fraction-exercise

### ISSUE THREAD

**Issue by gorelhedin** [lunduniversity/schoolprog#13]
I am writing up an exercise to help students with understanding fractions. It is

- in Swedish
- for both Scala and Python
- fragmented into a number of small pages, to do things step by step

Stuff left to do:

 - [x] Move pages about tuples, functions, main programs to separate directory.
 - [x] Complete it (there are some missing parts)
 - [x] Construct solutions
 - [x] Debug the instructions (I'm sure there are mistakes, didn't try to run it yet)

More to do, after meeting on Feb 7 2018:

- [x] Byt länk (fortsätt här) till att innehållet ligger under.
- [x] Se till att alla länkarna till extramaterial länkar tillbaka.
- [x] 2:4 (Otydligt vad vi menar här, skriv ut uppgift 2 av 4 istället)
- [x] Ta bort tuple och använd a, b, c, d direkt. Annars kommer vi förmodligen  tappa bort eleverna här.
- [x] Flödet genom uppgiften: länk för gå vidare (hoppa ner till efter övningen) istället för länk till övning.
- [x] Anpassa övningen - den behövs inte lika mycket nu när uppdraget Piece-of-cake finns.
- [x] Bland uppgifterna, förtydliga till: "Använd funktionen i föregående uppgift för att läsa in två bråk."
- [x] Ge eleverna några testfall, så de kan validera att de har gjort rätt.
- [x] Add suitable tags to both Fractions and Piece of Cake.

Piece-of-cake exercise:

- [x] Introduce new exercise Piece of Cake, that should precede this one
- [x] Comment on least common divisor
- [x] Construct solution and debug instructions

**Comment by gorelhedin** [comment]
Good enough for now. Closing this issue.

**Comment by exoji2e** [comment]
Maybe we can use `>! Spoiler text` construct in markdown, shown [here](https://meta.stackexchange.com/questions/1191/add-markdown-support-for-hidden-until-you-click-text-aka-spoilers) so we don't have to use separate pages and links.

However it does not seem to render correctly on github issues.

**Comment by gorelhedin** [comment]
In case `>! Spoiler text` doesn't work:  I found this advice for using the `<details>` tag and also to make it work on github Pages. It seems a bit tricky to get to work, and not ideal since you need to mix html and markdown. But might be an alternative. See https://github.com/gettalong/kramdown/issues/155

@ErikBjare we are trying to find a way for allowing all text of an exercise to be kept in the same file, and using some kind of spoiler technique to show more or less of the content. Perhaps you could make some experiments?

**Comment by ErikBjare** [comment]
I'd suggest using `<details>` for now. We can improve the styling of it later.

**Comment by gorelhedin** [comment]
<details> solution seems to work fine, both on github wiki and on the Jekyll Pages!!
