### ISSUE TITLE
Choice of REPL/IDE

### ISSUE THREAD

**Issue by ahnlabb** [lunduniversity/schoolprog#18]
We are currently using repl.it, in my opinion it fulfills our primary criteria:
- Simple/no setup
- Good interface (clean and intuitive)
- Easy and unlimited sharing of templates and example code

However, some other features would be nice:
- Full support of builtin modules (#9)
- SciPy, NumPy
- Plotting
- GUI support beyond plotting and turtle

I think we should discuss this before we are completely invested in repl.it.
Plotting is my foremost concern, can we do it with repl.it?

**Comment by ErikBjare** [comment]
You can plot with repl.it by saving the plot to a png file (which will show up in the file list).

Example: https://repl.it/@masonclayton/matplotlib-graph

**Comment by ahnlabb** [comment]
@ErikBjare silly of me to miss that, I even looked at that very example but didn't see where the file was created.

repl.it is probably our best bet then, the other things should not be necessary for basic programming education.

**Comment by ahnlabb** [comment]
For reference:
- [Skulpt](http://www.skulpt.org/)
- [trinket.io](https://trinket.io)

Both seem to me to have a bigger feature set (Skulpt has a slightly different scope) but might ultimately lack full python3 support and therefore not be viable alternatives.

**Comment by ErikBjare** [comment]
While we're on the topic, I'd like to write some article on how to get PyCharm setup for the students that want a more realistic development environment.

 - [ ] Write an article for how to get started with PyCharm

**Comment by amasad** [comment]
Hey there, sorry to intrude, I got an alert for Repl.it's mention. Just wanted to say that plotting does work (although we don't do a good job exposing it) and lots of people use it for machine learning, data science, and other applications.

**Comment by exoji2e** [comment]
@amasad Right now we are plotting by saving a png-file with `matplotlib.pyplot.savefig`. Do you support some kind of popup-window as well?

**Comment by amasad** [comment]
>@amasad Right now we are plotting by saving a png-file with matplotlib.pyplot.savefig. Do you support some kind of popup-window as well?

No, `savefig` is the best way to do it. Although we want to make it clear in the future for users that a new file appeared so that it kind of will work like a pop-up window.

**Comment by gorelhedin** [comment]
We need getting started guides for each online environment: Python-turtle, Python3, kojo-js.

- [ ] how to register (repl.it)
- [ ] screenshot of what it looks like
- [ ] what buttons to press
- [ ] how to save code

**Comment by gorelhedin** [comment]
Good enough for now.
