### ISSUE TITLE
Graphing Exercise

### ISSUE THREAD

**Issue by perssonsimon1** [lunduniversity/schoolprog#23]
Exercise teching how to plot different functions in python. Can probably take some inspiration from this [video](https://www.youtube.com/watch?v=7fkIZ0I59Eo).

**Comment by gorelhedin** [comment]
Found another video (the first seems blocked): https://www.youtube.com/watch?v=OFzqDatEvCo
There is a new exercises for this now: functional-strawman. Closing this issue.
