### ISSUE TITLE
Math Exerciser

### ISSUE THREAD

**Issue by gorelhedin** [lunduniversity/schoolprog#26]
@ahnlabb The exercise looks very nice. But the initial gif link seems broken, at least when looking at https://lunduniversity.github.io/schoolprog/exercises/math-exerciser/. I think you can make it work by using https://media.githubusercontent.com/media/ahnlabb/schoolprog-external/master/math-exerciser.gif instead.

I came to think of a better solution. Copy the gif file to the math-exerciser directory and make a local link to it.

**Comment by ahnlabb** [comment]
Thank you for catching this @gorelhedin, I've fixed it in accordance with your first suggestion and created a separate issue for the discussion of the proper way to do this going forward. I agree that relative links would be much nicer. Closing.
