### ISSUE TITLE
Handling of media

### ISSUE THREAD

**Issue by ahnlabb** [lunduniversity/schoolprog#27]
There are three ways that we could handle binary media (typically I guess images/gifs):
- Plain git
    - **pros**: 
        - simplest
        - relative links
        - versioning
    - **cons**:
        - full change history can get big and every repo has to always download the whole thing
- git-lfs (or similar)
    - **pros**:
        - relative links
        - versioning
    - **cons**:
        - some setup
        - public forks can't use git-lfs independently [(?)](https://github.com/git-lfs/git-lfs/issues/1906)
- Separate hosting
    - **pros**:
        - media handling not limited by git (which was not created for large binary files)
    - **cons**:
        - no relative links
        - solution dependent cons may include: no versioning, reliance on another 3rd-party service in addition to GH etc.

In `math-exerciser` I went with "separate hosting" where I still used github but created a new repo with git-lfs where I put the gif, this solution has versioning and no reliance on other 3rd-party services but critically **does not allow for relative links** (see #26). Depending on the amount of media (and maybe more importantly media **changes**) we expect just using plain git may be entirely feasible. What do you think @ErikBjare?

**Comment by gorelhedin** [comment]
Good point. I think we could have plain git if the files are small enough. What should in that case be the limit? 50k per file? I have a number of png files in the piece-of-cake exercise that are between 7 and 23 k.

For larger files, it would be good if we could store them somehow on the lunduniversity organization. I don't know what support there is for this on GH. Perhaps simply use a separate repository for binaries, and that is not intended to be cloned?

**Comment by gorelhedin** [comment]
Works ok for now. We commit small binaries.
