### ISSUE TITLE
Guidelines for repository contributors

### ISSUE THREAD

**Issue by ahnlabb** [lunduniversity/schoolprog#34]
Wherever we are on further recruitment (#4) we should probably add some contribution guidelines. Reasons to do this include:
- Clarify the scope of the project to ourselves and others
- Help teachers or various testers create good issues
- Encourage external people with ideas for great exercises to submit them as issues or pull requests
- Expound our overarching goals

Towards this goal we could add any subset of:
- [CONTRIBUTING](https://help.github.com/articles/setting-guidelines-for-repository-contributors/) file
- wiki pages
- site pages

**Comment by gorelhedin** [comment]
Good idea.
For the teachers participating in the workshops, I have created a google group: https://groups.google.com/forum/#!forum/lusp-vt-2018 where they can post questions about the exercises.
