### ISSUE TITLE
Weather data exercise

### ISSUE THREAD

**Issue by exoji2e** [lunduniversity/schoolprog#35]
There is currently a dataset and some ideas for tasks in `/exercises/weatherdata`. 
What needs to be done is:

- [ ] write task descriptions
- [ ] think through what 3rd party libraries should be used. Maybe `datetime` would make it easier to plot?
- [ ] think through the order of tasks and what hints are reasonable to give.
- [ ] write a solution for all tasks
- [ ] make a repl.it env that contains the api-code. (That opens the zipped data, etc) 

Feel free to help me with this. I might start on something of the above, and Ill write so here in that case!

**Comment by gorelhedin** [comment]
This work will be continued in the new repo schoolprog-satellite, so closing this issue.
