### ISSUE TITLE
Investigate Skolverket's web course for teachers

### ISSUE THREAD

**Issue by ErikBjare** [lunduniversity/schoolprog#5]
Discussed with @perssonsimon1 briefly in chat, we are confident that there will be some way to access the content: https://www.skolverket.se/kompetens-och-fortbildning/larare/om-programmering-webbkurs-1.263574

**Comment by gorelhedin** [comment]
It is possible to register an account at Skolverket and get access. I have done that and looked at some of the videos. It looks like nice material.

**Comment by ErikBjare** [comment]
We talked about this during a meeting a while back. Closing.
