### ISSUE TITLE
[weatherdata] repl.it does not seem to support http-requests

### ISSUE THREAD

**Issue by exoji2e** [lunduniversity/schoolprog#9]
I'm getting long errors when I try to use the API in #8 on repl, [here is a version on repl](https://repl.it/@exoji2e/WorstInsistentKoalabear)

I see some solutions:
1. We upload some weatherdata to repl.it
    + We can't upload everything, since it's about 500MB in raw format.
    + The students can't explore other weather stations (like their home town)
    + The students can't extend the API, making the exercise quite limited, and maybe not suited to be a week long project.
2. We find another site where it's possible to run python, and do http-requests
    + http://quintagroup.com/cms/python/online-interpreter
    + Maybe they are not as easy to get going as repl.it.
3. We do an offline version, where they run python locally
    + We get the entire installation-problem

I think we should check out some other sites, and if we don't find anything suitable, we should do both 1 and 3.

**Comment by ErikBjare** [comment]
I'm assuming HTTP.requests are disabled for security reasons, I'd expect every other good online REPL to have the same restrictions.

I think the best option is to simply give them a subset of the data, you could also gzip the file and extract it within the program (I think there are easy ways to do so in Python).

**Comment by exoji2e** [comment]
Yes, I'll see what I can get it down to. The raw historical data is only exposed as csv.

**Comment by exoji2e** [comment]
OK, I formatted all the weather data to lines on the format:
"{} {} {} {}".format(y, m, d, temp), with a header describing the weather station.
This gets the raw data down to 100MB, and a compressed version down to 28MB.

This repl.it accepts, but the webpage crashes if you click on the large compressed file. 
I still need to investigate if repl gives us enough memory to read it.

**Comment by ahnlabb** [comment]
The code works on [Trinket](https://trinket.io/). They also have turtle, matplotlib and pygal. However they don't have free 'unlimited python 3 Trinkets' whatever that means. I like repl.it but the plotting features would be really nice. I'll open an issue for the discussion of an alternative in browser REPL/IDE.

**Comment by gorelhedin** [comment]
The weatherdata exercise will be continued in a new repo schoolprog-satellite, so I'm closing this issue.
